# Generated by Django 4.0 on 2021-12-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowerstalk', '0002_items_delete_flowers'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
