# Generated by Django 4.0 on 2022-01-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowerstalk', '0004_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Product',
        ),
    ]
