# Generated by Django 4.0 on 2022-01-07 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_city_order_options_order_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='lga',
        ),
    ]
