# Generated by Django 4.0 on 2022-01-11 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Date of Payment')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='images/%Y/%m/')),
                ('orderItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='orders.orderitem')),
            ],
        ),
    ]
