# Generated by Django 4.0 on 2022-01-11 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_paymentupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentupload',
            name='orderItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='orders.order'),
        ),
    ]
