# Generated by Django 4.0 on 2022-01-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_paymentupload_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/'),
        ),
    ]
