# Generated by Django 4.0 on 2022-01-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_paymentupload_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='personalized_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
