# Generated by Django 4.0 on 2022-01-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_personalized_note'),
        ('orders', '0009_alter_order_phone'),
    ]

    operations = [
    ]
